// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mainParqueo;

#nullable disable

namespace mainParqueo.Migrations
{
    [DbContext(typeof(ConexionBD))]
    [Migration("20250903161122_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("mainParqueo.Logs", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_vehiculo_fk")
                        .HasColumnType("int");

                    b.Property<string>("placa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("id_vehiculo_fk");

                    b.ToTable("LOGS", (string)null);
                });

            modelBuilder.Entity("mainParqueo.Ocupacion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("Entrada")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_spot_fk")
                        .HasColumnType("int");

                    b.Property<int>("id_vehiculo_fk")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("id_spot_fk");

                    b.HasIndex("id_vehiculo_fk");

                    b.ToTable("OCUPACION", (string)null);
                });

            modelBuilder.Entity("mainParqueo.Parqueo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("capacidadLey7600")
                        .HasColumnType("int");

                    b.Property<int>("capacidadMaxima")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("PARQUEO", (string)null);
                });

            modelBuilder.Entity("mainParqueo.Roles", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("ROLES", (string)null);
                });

            modelBuilder.Entity("mainParqueo.RolesUsuario", b =>
                {
                    b.Property<int>("id_rol_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_rol_usuario"));

                    b.Property<int>("id_role_fk")
                        .HasColumnType("int");

                    b.Property<int>("id_usuario_fk")
                        .HasColumnType("int");

                    b.HasKey("id_rol_usuario");

                    b.HasIndex("id_role_fk");

                    b.HasIndex("id_usuario_fk");

                    b.ToTable("ROLESUSUARIO", (string)null);
                });

            modelBuilder.Entity("mainParqueo.Spots", b =>
                {
                    b.Property<int>("id_spot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_spot"));

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<int>("Parqueo_id_fk")
                        .HasColumnType("int");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_spot");

                    b.HasIndex("Parqueo_id_fk");

                    b.ToTable("SPOTS", (string)null);
                });

            modelBuilder.Entity("mainParqueo.Usuario", b =>
                {
                    b.Property<int>("id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_usuario"));

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(110)
                        .HasColumnType("nvarchar(110)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("id_usuario");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("usuario")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("mainParqueo.Vehiculos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("id_parqueo_fk")
                        .HasColumnType("int");

                    b.Property<int>("id_usuario_fkVehiculo")
                        .HasColumnType("int");

                    b.Property<string>("marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("placa")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("id_parqueo_fk");

                    b.HasIndex("id_usuario_fkVehiculo");

                    b.HasIndex("placa")
                        .IsUnique();

                    b.ToTable("VEHICULOS", (string)null);
                });

            modelBuilder.Entity("mainParqueo.Logs", b =>
                {
                    b.HasOne("mainParqueo.Vehiculos", "vehiculos")
                        .WithMany()
                        .HasForeignKey("id_vehiculo_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("vehiculos");
                });

            modelBuilder.Entity("mainParqueo.Ocupacion", b =>
                {
                    b.HasOne("mainParqueo.Spots", "Spots")
                        .WithMany()
                        .HasForeignKey("id_spot_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mainParqueo.Vehiculos", "Vehiculos")
                        .WithMany()
                        .HasForeignKey("id_vehiculo_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spots");

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("mainParqueo.RolesUsuario", b =>
                {
                    b.HasOne("mainParqueo.Roles", "roles")
                        .WithMany()
                        .HasForeignKey("id_role_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mainParqueo.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("id_usuario_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("roles");
                });

            modelBuilder.Entity("mainParqueo.Spots", b =>
                {
                    b.HasOne("mainParqueo.Parqueo", "Parqueo")
                        .WithMany()
                        .HasForeignKey("Parqueo_id_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parqueo");
                });

            modelBuilder.Entity("mainParqueo.Vehiculos", b =>
                {
                    b.HasOne("mainParqueo.Parqueo", "Parqueo")
                        .WithMany()
                        .HasForeignKey("id_parqueo_fk");

                    b.HasOne("mainParqueo.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("id_usuario_fkVehiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parqueo");

                    b.Navigation("usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
