@MiprimerApi_sin_apiController__HostAddress = http://localhost:5026

# GET {{MiprimerApi_sin_apiController__HostAddress}}/weatherforecast/
GET {{MiprimerApi_sin_apiController__HostAddress}}/weatherforecast/
Accept: application/json

###
